using global::System.Text.Json;
using global::System.Text.Json.Serialization;
using Vapi.Net.Core;

namespace Vapi.Net;

[Serializable]
public record AssistantMessage : IJsonOnDeserialized
{
    [JsonExtensionData]
    private readonly IDictionary<string, JsonElement> _extensionData =
        new Dictionary<string, JsonElement>();

    /// <summary>
    /// This is the role of the message author
    /// </summary>
    [JsonPropertyName("role")]
    public required AssistantMessageRole Role { get; set; }

    /// <summary>
    /// This is the content of the assistant message
    /// </summary>
    [JsonPropertyName("content")]
    public string? Content { get; set; }

    /// <summary>
    /// This is the refusal message generated by the model
    /// </summary>
    [JsonPropertyName("refusal")]
    public string? Refusal { get; set; }

    /// <summary>
    /// This is the tool calls generated by the model
    /// </summary>
    [JsonPropertyName("tool_calls")]
    public IEnumerable<ToolCall>? ToolCalls { get; set; }

    /// <summary>
    /// This is an optional name for the participant
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>
    /// This is an optional metadata for the message
    /// </summary>
    [JsonPropertyName("metadata")]
    public object? Metadata { get; set; }

    [JsonIgnore]
    public ReadOnlyAdditionalProperties AdditionalProperties { get; private set; } = new();

    void IJsonOnDeserialized.OnDeserialized() =>
        AdditionalProperties.CopyFromExtensionData(_extensionData);

    /// <inheritdoc />
    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
