using System.Text.Json;
using System.Text.Json.Serialization;
using Vapi.Net.Core;

namespace Vapi.Net;

[Serializable]
public record TransferAssistant
{
    /// <summary>
    /// Optional name for the transfer assistant
    /// </summary>
    [JsonPropertyName("name")]
    public string? Name { get; set; }

    /// <summary>
    /// Model configuration for the transfer assistant
    /// </summary>
    [JsonPropertyName("model")]
    public required TransferAssistantModel Model { get; set; }

    /// <summary>
    /// This is the first message that the transfer assistant will say.
    /// This can also be a URL to a custom audio file.
    ///
    /// If unspecified, assistant will wait for user to speak and use the model to respond once they speak.
    /// </summary>
    [JsonPropertyName("firstMessage")]
    public string? FirstMessage { get; set; }

    /// <summary>
    /// This is the mode for the first message. Default is 'assistant-speaks-first'.
    ///
    /// Use:
    /// - 'assistant-speaks-first' to have the assistant speak first.
    /// - 'assistant-waits-for-user' to have the assistant wait for the user to speak first.
    /// - 'assistant-speaks-first-with-model-generated-message' to have the assistant speak first with a message generated by the model based on the conversation state.
    ///
    /// @default 'assistant-speaks-first'
    /// </summary>
    [JsonPropertyName("firstMessageMode")]
    public TransferAssistantFirstMessageMode? FirstMessageMode { get; set; }

    /// <summary>
    /// This is the maximum duration in seconds for the transfer assistant conversation.
    /// After this time, the transfer will be cancelled automatically.
    /// @default 120
    /// </summary>
    [JsonPropertyName("maxDurationSeconds")]
    public double? MaxDurationSeconds { get; set; }

    /// <summary>
    /// This is the number of seconds of silence to wait before ending the call. Defaults to 30.
    ///
    /// @default 30
    /// </summary>
    [JsonPropertyName("silenceTimeoutSeconds")]
    public double? SilenceTimeoutSeconds { get; set; }

    /// <summary>
    /// Additional properties received from the response, if any.
    /// </summary>
    /// <remarks>
    /// [EXPERIMENTAL] This API is experimental and may change in future releases.
    /// </remarks>
    [JsonExtensionData]
    public IDictionary<string, JsonElement> AdditionalProperties { get; internal set; } =
        new Dictionary<string, JsonElement>();

    /// <inheritdoc />
    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
